spring:
  datasource:
    url: jdbc:mysql://localhost:3306/battleship
    username: your_username
    password: your_password
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
